[package]
name = "harness"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
data-service-core = { path = "../data-service-core" }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }
zstd = { workspace = true }
flate2 = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
