[package]
name = "latency-bench"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
data-service-core = { path = "../data-service-core" }
evm-source = { path = "../evm-source" }
rpc-client = { path = "../rpc-client" }
tokio = { workspace = true }
futures = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
zstd = { workspace = true }
flate2 = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
